apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: xceler-ui
  namespace: devops-platform-2
spec:
  project: default
  source:
    repoURL: https://github.com/AniirudhA/xceler-ui
    targetRevision: anirudhtask-2
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: devops-platform-2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    
